from playwright.sync_api import Page, expect


def test_full_create_entity(page: Page, base_url: str) -> None:
    page.goto(base_url)
    page.get_by_role("button", name="User Button / Profile").click()
    page.get_by_role("button", name="Login").click()
    page.get_by_role("textbox", name="email").click()
    page.get_by_role("textbox", name="email").fill("alban@mail.com")
    page.get_by_role("textbox", name="email").press("Tab")
    page.get_by_role("textbox", name="password").fill("azer")
    page.get_by_role("button", name="Log In").click()
    page.get_by_role("button", name="Commencez maintenant !").click()
    expect(page.get_by_role("button", name="Royaume de Boréalis")).to_be_visible()
    page.get_by_role("button", name="Royaume de Boréalis").click()
    page.get_by_role("button", name="Royaume de Boréalis").click()
    page.get_by_role("button", name="Forêt d'Ébène").click()
    expect(page.get_by_role("heading", name="Forêt d'Ébène")).to_be_visible()
    expect(page.locator("#root")).to_contain_text("Forêt d'Ébène")
    page.get_by_role("button", name="Create Entity").click()
    page.get_by_role("textbox", name="entityName").click()
    page.get_by_role("textbox", name="entityName").fill("L'arbre Primaire")
    page.get_by_role("textbox", name="entityNotDiscoveredName").click()
    page.get_by_role("textbox", name="entityNotDiscoveredName").fill("Grand Arbre")
    page.get_by_role("button", name="Create", exact=True).click()
    expect(page.get_by_role("button", name="L'arbre Primaire")).to_be_visible()
    expect(page.get_by_role("listitem")).to_contain_text("L'arbre Primaire")
    page.get_by_role("button", name="L'arbre Primaire").click()
    expect(page.locator("#root")).to_contain_text("L'arbre Primaire")
    expect(page.get_by_role("heading", name="L'arbre Primaire")).to_be_visible()
