CREATE TYPE "commits_status" AS ENUM (
  'pending',
  'accepted',
  'rejected'
);

CREATE TYPE "invitation_status" AS ENUM (
  'pending',
  'accepted',
  'rejected'
);

CREATE TYPE "user_universe_role" AS ENUM (
  'creator',
  'super administrator'
);

CREATE TYPE "user_entity_role" AS ENUM (
  'entity administrator',
  'editor'
);

CREATE TABLE "session_token" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" varchar(255) UNIQUE NOT NULL,
  "user_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT 'now()',
  "updated_at" timestamp NOT NULL,
  "expires_at" timestamp NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "username" varchar(255) UNIQUE NOT NULL,
  "bio" text,
  "picture" bytea,
  "created_at" timestamp NOT NULL DEFAULT 'now()',
  "updated_at" timestamp
);

CREATE TABLE "universe" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "creator_id" int NOT NULL,
  "name" varchar(255),
  "description" text,
  "version" varchar(255),
  "created_at" timestamp NOT NULL DEFAULT 'now()',
  "updated_at" timestamp
);

CREATE TABLE "invitations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_id" integer NOT NULL,
  "receiver_id" integer NOT NULL,
  "universe_id" integer NOT NULL,
  "status" invitation_status NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT 'now()',
  "updated_at" timestamp
);

CREATE TABLE "entities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "not_discovered_name" varchar(255) DEFAULT '???',
  "name" varchar(255) NOT NULL,
  "parent" int,
  "universe_id" int NOT NULL,
  "creator_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT 'now()',
  "updated_at" timestamp
);

CREATE TABLE "text_blocks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255),
  "content" text,
  "creator_id" int NOT NULL,
  "entity_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT 'now()',
  "updated_at" timestamp
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text NOT NULL,
  "creator_id" int NOT NULL,
  "entity_id" int NOT NULL,
  "text_block_id" int,
  "comment_id" int,
  "created_at" timestamp NOT NULL DEFAULT 'now()',
  "updated_at" timestamp
);

CREATE TABLE "commits" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message" text,
  "creator_id" int NOT NULL,
  "content" json,
  "status" commits_status,
  "admin_comment" text
);

CREATE TABLE "differences" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE "user_universe" (
  "user_id" int NOT NULL,
  "universe_id" int NOT NULL,
  "admin_role" user_universe_role,
  PRIMARY KEY ("user_id", "universe_id")
);

CREATE TABLE "user_text_block" (
  "user_id" int NOT NULL,
  "text_block_id" int NOT NULL,
  PRIMARY KEY ("user_id", "text_block_id")
);

CREATE TABLE "user_entity" (
  "user_id" int NOT NULL,
  "entity_id" int NOT NULL,
  "role" user_entity_role,
  PRIMARY KEY ("user_id", "entity_id")
);

COMMENT ON TABLE "session_token" IS 'Token to keep user connected.';

COMMENT ON TABLE "users" IS 'A user of MyUniverseDoc';

COMMENT ON TABLE "universe" IS 'The main object. It represent a universe or something similary';

COMMENT ON TABLE "invitations" IS 'created when the universe''s creator or superadmin invite an other user.';

COMMENT ON COLUMN "invitations"."sender_id" IS 'fk: The one who sends the invitation';

COMMENT ON COLUMN "invitations"."receiver_id" IS 'fk: The one who receives the invitation';

COMMENT ON COLUMN "invitations"."universe_id" IS 'fk: the universe the invitation is for';

COMMENT ON TABLE "entities" IS 'An object in the universe. It can be parent of other entities and child of an other entity.';

COMMENT ON COLUMN "entities"."not_discovered_name" IS 'the name shown if the user as reader can see a text_block of this entity, but the name is unknown';

COMMENT ON TABLE "text_blocks" IS 'contains text and permit who can see it';

COMMENT ON COLUMN "text_blocks"."content" IS 'suppose to be in markdown';

COMMENT ON TABLE "comments" IS 'comments let by users';

COMMENT ON COLUMN "comments"."text_block_id" IS 'if null, the comment is about the whole entity';

COMMENT ON COLUMN "comments"."comment_id" IS 'In case of response';

COMMENT ON TABLE "commits" IS 'the modifications sent by an editor that must be checked by an admin';

COMMENT ON TABLE "differences" IS 'an object that specifies what are the differences between the ancients and the new entity
';

COMMENT ON TABLE "user_universe" IS 'Identify the user''s role about this universe.';

COMMENT ON COLUMN "user_universe"."admin_role" IS 'creator : the creator of this universe. He obviously can do anything about it.
super administrator : such like a moderator, has the same power as the creator except elevating/deleting someone as super administrator
';

COMMENT ON TABLE "user_text_block" IS 'If exists, the user can read the text block';

COMMENT ON TABLE "user_entity" IS 'Identify the user''s role about this entity and its children';

COMMENT ON COLUMN "user_entity"."role" IS 'entity administrator : the user has an overview about what happens and can choose who can see and edit in this entity and its children. He can modify the entity without verification.
editor : the user can see everything about this entity and its children. He can edit those entities, however each update must be approvate by entity administrator, super administrator or creator  ';

ALTER TABLE "session_token" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "universe" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id");

ALTER TABLE "invitations" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");

ALTER TABLE "invitations" ADD FOREIGN KEY ("receiver_id") REFERENCES "users" ("id");

ALTER TABLE "invitations" ADD FOREIGN KEY ("universe_id") REFERENCES "universe" ("id");

ALTER TABLE "entities" ADD FOREIGN KEY ("id") REFERENCES "entities" ("parent");

ALTER TABLE "entities" ADD FOREIGN KEY ("universe_id") REFERENCES "universe" ("id");

ALTER TABLE "entities" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id");

ALTER TABLE "text_blocks" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id");

ALTER TABLE "text_blocks" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("text_block_id") REFERENCES "text_blocks" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("comment_id") REFERENCES "comments" ("id");

ALTER TABLE "commits" ADD FOREIGN KEY ("creator_id") REFERENCES "users" ("id");

ALTER TABLE "user_universe" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_universe" ADD FOREIGN KEY ("universe_id") REFERENCES "universe" ("id");

ALTER TABLE "user_text_block" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_text_block" ADD FOREIGN KEY ("text_block_id") REFERENCES "text_blocks" ("id");

ALTER TABLE "user_entity" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_entity" ADD FOREIGN KEY ("entity_id") REFERENCES "entities" ("id");
